// <auto-generated />
using System;
using ChallengeCounter.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChallengeCounter.Api.Database.Migrations
{
    [DbContext(typeof(WorkoutLogDbContext))]
    [Migration("20250701130559_AddUserGoal")]
    partial class AddUserGoal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChallengeCounter.Api.Database.Models.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsGoal")
                        .HasColumnType("integer")
                        .HasColumnName("abs_goal");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("PushupsGoal")
                        .HasColumnType("integer")
                        .HasColumnName("pushups_goal");

                    b.Property<int>("SquatsGoal")
                        .HasColumnType("integer")
                        .HasColumnName("squats_goal");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_user_goal");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_user_goal_user_id_year_month");

                    b.ToTable("user_goal", (string)null);
                });

            modelBuilder.Entity("ChallengeCounter.Api.Database.Models.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Abs")
                        .HasColumnType("integer")
                        .HasColumnName("abs");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExerciseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exercise_date");

                    b.Property<int>("Pushups")
                        .HasColumnType("integer")
                        .HasColumnName("pushups");

                    b.Property<int>("Squats")
                        .HasColumnType("integer")
                        .HasColumnName("squats");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_log");

                    b.ToTable("workout_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
