// <auto-generated />
using System;
using ChallengeCounter.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChallengeCounter.Api.Migrations
{
    [DbContext(typeof(WorkoutLogDbContext))]
    partial class WorkoutLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChallengeCounter.Api.Database.Models.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Abs")
                        .HasColumnType("integer")
                        .HasColumnName("abs");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExerciseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exercise_date");

                    b.Property<int>("Pushups")
                        .HasColumnType("integer")
                        .HasColumnName("pushups");

                    b.Property<int>("Squats")
                        .HasColumnType("integer")
                        .HasColumnName("squats");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_log");

                    b.ToTable("workout_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
